apiVersion: v2
name: mautrix-whatsapp
description: A Matrix-WhatsApp puppeting bridge
type: application
version: 1.0.0
# renovate: image=dock.mau.dev/mautrix/whatsapp
appVersion: "v0.8.1"
keywords:
  - matrix
  - whatsapp
  - bridge
home: https://github.com/pree/helm-charts/tree/master/charts/mautrix-whatsapp
sources:
  - https://github.com/mautrix/whatsapp
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.1
  - name: postgresql
    version: 12.1.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: init
