clusterplex:
  enabled: true
  values:
    global:
      timezone: "Europe/Berlin"

      sharedStorage:
        transcode:
          enabled: false

        media:
          enabled: true
          existingClaim: "media"

    pms:
      enabled: true
      config:
        transcodeOperatingMode: "local"
        plexClaimToken: "plexclaim-token"
        version: "latest"
        localRelayEnabled: false

      serviceConfig:
        externalTrafficPolicy: "local"

      ingressConfig:
        enabled: false

      configVolume:
        enabled: true
        storageClass: "default"
        size: "25Gi"

    orchestrator:
      enabled: false

    worker:
      enabled: false
